### ISSUE TITLE
Deprecated attribute in compose files 

### ISSUE THREAD

**Issue by BilousVladyslav** [bandirom/django-template#33]
According to [compose file specification](https://docs.docker.com/compose/compose-file/#compose-file), the `version` attribute become deprecated and should not be included in Compose file implementations. 

Here is an example of affected code:

```
version: "3.7"

x-variables: &variables
  ENV_STAGE: local

services:
  web:
  ...
```

Pull request with all `version` attributes removed is attached. 
#32
